services:

    nginx:
        container_name: 'nginx'
        image: nginx:latest
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - app
        networks:
            - sail
        restart: always

    app:
        container_name: 'backend'
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - './backend/:/var/www/html'
        depends_on:
            - mariadb
        networks:
            - sail
        restart: always

    mariadb:
        container_name: 'db'
        image: 'mariadb:10'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'test'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'dev'
            MYSQL_PASSWORD: 'test'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './docker/mariadb:/var/lib/mysql'
        networks:
            - sail
        restart: always

    frontend:
        container_name: 'react'
        build:
            context: ./frontend
        ports:
            - "80:80"
        networks:
            - sail
        restart: always

    # redis:
    #     container_name: 'cache'
    #     image: 'redis:alpine'
    #     ports:
    #         - '6379:6379'
    #     volumes:
    #         - './docker/redis:/data'
    #     networks:
    #         - sail
networks:
    sail:
        driver: bridge